version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-native-paper
    versions:
    - 4.8.0
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.17
  - dependency-name: "@react-navigation/stack"
    versions:
    - 5.14.4
  - dependency-name: "@react-navigation/native"
    versions:
    - 5.9.3
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
  - dependency-name: react-native-reanimated
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: metro-react-native-babel-preset
    versions:
    - 0.65.2
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.2
